services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
#      - DATABASE_URL=postgres://user:password@db:5432/movie_monkey_db
#    depends_on:
#      - db
    restart: unless-stopped

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: movie_monkey_db
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
